<wsdl:definitions
     name="Insert_WorkflowAuditDetail"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/UtilitiesApplication/WorkflowCustomAuditHandlerProject/Insert_WorkflowAuditDetail"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/UtilitiesApplication/WorkflowCustomAuditHandlerProject/Insert_WorkflowAuditDetail"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Insert_WorkflowAuditDetail_plt" >
    <plt:role name="Insert_WorkflowAuditDetail_role" >
      <plt:portType name="tns:Insert_WorkflowAuditDetail_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail" schemaLocation="../Schemas/Insert_WorkflowAuditDetail_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TWorkflowAuditdetailCollection_msg">
        <wsdl:part name="TWorkflowAuditdetailCollection" element="top:TWorkflowAuditdetailCollection"/>
    </wsdl:message>
    <wsdl:portType name="Insert_WorkflowAuditDetail_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TWorkflowAuditdetailCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
