<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/RecordBPMTaskCreation"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/RecordBPMTaskCreation"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="RecordBPMTaskCreationBPEL">
        <plnk:role name="RecordBPMTaskCreationPortType" portType="tns:RecordBPMTaskCreationPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/RecordBPMTaskCreation"
         location="oramds:/apps/SOABundles/WSDL/UtilityService/RecordBPMTaskCreation.wsdl"/>
</wsdl:definitions>
