<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAudit_Tab"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:ns0="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"
                xmlns:ns1="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/InitiateWorkflowAudit"
                xmlns:ns2="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmisWorkflowFault"
                xmlns:ns3="http://newmmis.eohhs.ma.gov/worklist/xml"
                xmlns:ns4="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmiscommon"
                xmlns:ns6="http://newmmis.eohhs.ma.gov/workflows/xml"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns7="http://xmlns.oracle.com/pcbpel/adapter/db/UtilitiesApplication/WorkflowCustomAuditHandlerProject/Insert_WorkflowAudit_Tab"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOABundles/WSDL/UtilityService/InitiateWorkflowAudit.wsdl"/>
        <oracle-xsl-mapper:rootElement name="initiateWorkflowAuditRequest"
                                       namespace="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Insert_WorkflowAudit_Tab.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TWorkflowAuditCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAudit_Tab"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.2(XSLT Build 150402.0900.0103) AT [MON JUL 06 13:35:31 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="in"
                  select='dvm:lookupValue1M ("oramds:/apps/SOABundles/DVM/WorkFlowProperties.dvm", "WorkflowID", /ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID, "BusinessKey" )'/>
    <tns:TWorkflowAuditCollection>
      <tns:TWorkflowAudit>
        <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID">
          <tns:sakWorkflow>
            <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID"/>
          </tns:sakWorkflow>
        </xsl:if>
        <tns:namKeyproperty>
          <xsl:value-of select='dvm:lookupValue1M ("oramds:/apps/SOABundles/DVM/WorkFlowProperties.dvm", "WorkflowID", /ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID, "BusinessKey" )'/>
        </tns:namKeyproperty>
        <tns:idKeyproperty>
          <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME=$in]/ns6:PROPERTYVALUE"/>
        </tns:idKeyproperty>
        <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:creationDate">
          <tns:dteCreation>
            <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:creationDate"/>
          </tns:dteCreation>
        </xsl:if>
        <tns:cdeWorkflowstatus>IN PROGRESS</tns:cdeWorkflowstatus>
        <tns:indReadyforpurge>N</tns:indReadyforpurge>
        <tns:indPurged>N</tns:indPurged>
        <tns:tWorkflowAuditdetailCollection>
          <tns:TWorkflowAuditdetail>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns0:GUID">
              <tns:idGuid>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns0:GUID"/>
              </tns:idGuid>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns0:ECID">
              <tns:idEcid>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns0:ECID"/>
              </tns:idEcid>
            </xsl:if>
            <tns:cdeWorkflowAction>I</tns:cdeWorkflowAction>
            <tns:dteActivitystart>
              <xsl:value-of select="xp20:current-dateTime ( )"/>
            </tns:dteActivitystart>
            <tns:dteActivitycompletion/>
            <tns:txtActivitypayload>
              <xsl:copy-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML"/>
            </tns:txtActivitypayload>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns0:messageContext/ns4:businessUser">
              <tns:idClerk>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns0:messageContext/ns4:businessUser"/>
              </tns:idClerk>
            </xsl:if>
            <tns:txtAssignee>
              <xsl:value-of select="concat (/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:assignee/ns3:user, ',',/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:assignee/ns3:group )"/>
            </tns:txtAssignee>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID">
              <tns:sakWorkflow>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:WORKFLOWID"/>
              </tns:sakWorkflow>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='WorkflowStatusID']/ns6:PROPERTYVALUE">
              <tns:sakStatus>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='WorkflowStatusID']/ns6:PROPERTYVALUE"/>
              </tns:sakStatus>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Status']/ns6:PROPERTYVALUE">
              <tns:namStatus>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Status']/ns6:PROPERTYVALUE"/>
              </tns:namStatus>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='WorkflowQueueID']/ns6:PROPERTYVALUE">
              <tns:sakQueue>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='WorkflowQueueID']/ns6:PROPERTYVALUE"/>
              </tns:sakQueue>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Queue']/ns6:PROPERTYVALUE">
              <tns:namQueue>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Queue']/ns6:PROPERTYVALUE"/>
              </tns:namQueue>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Tracking Number']/ns6:PROPERTYVALUE">
              <tns:txtTrackingnumber>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Tracking Number']/ns6:PROPERTYVALUE"/>
              </tns:txtTrackingnumber>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PA Number']/ns6:PROPERTYVALUE">
              <tns:txtPanumber>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PA Number']/ns6:PROPERTYVALUE"/>
              </tns:txtPanumber>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Assignment']/ns6:PROPERTYVALUE">
              <tns:txtAssignment>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Assignment']/ns6:PROPERTYVALUE"/>
              </tns:txtAssignment>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Date Received']/ns6:PROPERTYVALUE !='-' ">
              <tns:dteDatereceived>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Date Received']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteDatereceived>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Cornelius Due Date']/ns6:PROPERTYVALUE !='-'">
              <tns:dteCorneliusduedate>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Cornelius Due Date']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteCorneliusduedate>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Member ID']/ns6:PROPERTYVALUE">
              <tns:txtMemberid>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Member ID']/ns6:PROPERTYVALUE"/>
              </tns:txtMemberid>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Attach Ind']/ns6:PROPERTYVALUE">
              <tns:txtAttachid>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Attach Ind']/ns6:PROPERTYVALUE"/>
              </tns:txtAttachid>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PAS Number']/ns6:PROPERTYVALUE">
              <tns:txtPasnumber>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PAS Number']/ns6:PROPERTYVALUE"/>
              </tns:txtPasnumber>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Admission Date']/ns6:PROPERTYVALUE !='-'">
              <tns:dteAdmissiondate>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Admission Date']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteAdmissiondate>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Member Name']/ns6:PROPERTYVALUE">
              <tns:txtMembername>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Member Name']/ns6:PROPERTYVALUE"/>
              </tns:txtMembername>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Facility Name']/ns6:PROPERTYVALUE">
              <tns:txtFacilityname>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Facility Name']/ns6:PROPERTYVALUE"/>
              </tns:txtFacilityname>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Assigned Date']/ns6:PROPERTYVALUE != '-' ">
              <tns:dteAssigneddate>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Assigned Date']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteAssigneddate>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='MH Review Type']/ns6:PROPERTYVALUE">
              <tns:txtMhreviewtype>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='MH Review Type']/ns6:PROPERTYVALUE"/>
              </tns:txtMhreviewtype>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Deferred Date']/ns6:PROPERTYVALUE !='-'">
              <tns:dteDeffereddate>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Deferred Date']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteDeffereddate>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PCC']/ns6:PROPERTYVALUE">
              <tns:txtPcc>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='PCC']/ns6:PROPERTYVALUE"/>
              </tns:txtPcc>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Submission Type']/ns6:PROPERTYVALUE">
              <tns:txtSubmissiontype>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Submission Type']/ns6:PROPERTYVALUE"/>
              </tns:txtSubmissiontype>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Status Date']/ns6:PROPERTYVALUE !='-'">
              <tns:dteStatusdate>
                <xsl:call-template name="formatDate">
                  <xsl:with-param name="dateParam"
                                  select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Status Date']/ns6:PROPERTYVALUE"/>
                </xsl:call-template>
              </tns:dteStatusdate>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='NPI']/ns6:PROPERTYVALUE">
              <tns:txtNpi>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='NPI']/ns6:PROPERTYVALUE"/>
              </tns:txtNpi>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Service Location']/ns6:PROPERTYVALUE">
              <tns:txtServicelocation>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Service Location']/ns6:PROPERTYVALUE"/>
              </tns:txtServicelocation>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Provider Type']/ns6:PROPERTYVALUE">
              <tns:txtProvidertype>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Provider Type']/ns6:PROPERTYVALUE"/>
              </tns:txtProvidertype>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='DBA Name']/ns6:PROPERTYVALUE">
              <tns:txtDbaname>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='DBA Name']/ns6:PROPERTYVALUE"/>
              </tns:txtDbaname>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='SSN/FEIN']/ns6:PROPERTYVALUE">
              <tns:txtSsnFein>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='SSN/FEIN']/ns6:PROPERTYVALUE"/>
              </tns:txtSsnFein>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Internal ATN']/ns6:PROPERTYVALUE">
              <tns:txtInternalatn>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Internal ATN']/ns6:PROPERTYVALUE"/>
              </tns:txtInternalatn>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='External ATN']/ns6:PROPERTYVALUE">
              <tns:txtExternalatn>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='External ATN']/ns6:PROPERTYVALUE"/>
              </tns:txtExternalatn>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Reason Code']/ns6:PROPERTYVALUE">
              <tns:txtReasoncode>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Reason Code']/ns6:PROPERTYVALUE"/>
              </tns:txtReasoncode>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Document Type']/ns6:PROPERTYVALUE">
              <tns:txtDocumenttype>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Document Type']/ns6:PROPERTYVALUE"/>
              </tns:txtDocumenttype>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Update Type']/ns6:PROPERTYVALUE">
              <tns:txtUpdatetype>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Update Type']/ns6:PROPERTYVALUE"/>
              </tns:txtUpdatetype>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Provider ID/Loc']/ns6:PROPERTYVALUE">
              <tns:txtProvideridLoc>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='Provider ID/Loc']/ns6:PROPERTYVALUE"/>
              </tns:txtProvideridLoc>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='View Image']/ns6:PROPERTYVALUE">
              <tns:txtViewimage>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='View Image']/ns6:PROPERTYVALUE"/>
              </tns:txtViewimage>
            </xsl:if>
            <xsl:if test="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='SAK_PROV_XML']/ns6:PROPERTYVALUE">
              <tns:txtSakProvXml>
                <xsl:value-of select="/ns0:initiateWorkflowAuditRequest/ns6:WorkitemCreationXML/ns6:CustomPropertyType[ns6:PROPERTYNAME='SAK_PROV_XML']/ns6:PROPERTYVALUE"/>
              </tns:txtSakProvXml>
            </xsl:if>
          </tns:TWorkflowAuditdetail>
        </tns:tWorkflowAuditdetailCollection>
      </tns:TWorkflowAudit>
    </tns:TWorkflowAuditCollection>
  </xsl:template>
  <xsl:template name="formatDate">
    <xsl:param name="dateParam"/>
    <xsl:value-of select="concat(concat(substring($dateParam,7,4),'-',substring($dateParam,1,2),'-',substring($dateParam,4,2)),'T00:00:00.000Z')"/>
  </xsl:template>
</xsl:stylesheet>
