<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns4="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmiscommon"
                xmlns:ns1="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/UpdateWorkflowAudit"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:ns2="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmisWorkflowFault"
                xmlns:ns3="http://newmmis.eohhs.ma.gov/worklist/xml"
                xmlns:ns5="http://newmmis.eohhs.ma.gov/workflows/xml"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/UtilitiesApplication/WorkflowCustomAuditHandlerProject/Insert_WorkflowAuditDetail"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOABundles/WSDL/UtilityService/UpdateWorkflowAudit.wsdl"/>
        <oracle-xsl-mapper:rootElement name="updateWorkflowAuditRequest"
                                       namespace="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Insert_WorkflowAuditDetail.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TWorkflowAuditdetailCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.2(XSLT Build 150402.0900.0103) AT [TUE JUL 07 10:45:41 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:TWorkflowAuditdetailCollection>
      <tns:TWorkflowAuditdetail>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns0:sak_workflowaudit">
          <tns:sakWorkflowaudit>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:sak_workflowaudit"/>
          </tns:sakWorkflowaudit>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns0:GUID">
          <tns:idGuid>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:GUID"/>
          </tns:idGuid>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns0:TaskId">
          <tns:idTask>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:TaskId"/>
          </tns:idTask>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns0:ECID">
          <tns:idEcid>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:ECID"/>
          </tns:idEcid>
        </xsl:if>
        <xsl:choose>
        <xsl:when test="/ns0:updateWorkflowAuditRequest/ns0:ActionCd='D'">
          <tns:cdeWorkflowAction> <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:ActionCd"/></tns:cdeWorkflowAction>
        </xsl:when>
        <xsl:otherwise>
        <tns:cdeWorkflowAction>U</tns:cdeWorkflowAction>
        </xsl:otherwise>
        </xsl:choose>
        <tns:dteActivitystart>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:dteActivitystart>
        <tns:dteActivitycompletion/>
        <tns:txtActivitypayload>
          <xsl:copy-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML"/>
        </tns:txtActivitypayload>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns0:messageContext/ns4:businessUser">
          <tns:idClerk>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns0:messageContext/ns4:businessUser"/>
          </tns:idClerk>
        </xsl:if>
        <tns:txtAssignee>
          <xsl:value-of select='concat (/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns3:TaskUpdateXML/ns3:assignee/ns3:user, ",", /ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns3:TaskUpdateXML/ns3:assignee/ns3:group )'/>
        </tns:txtAssignee>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:WORKFLOWID">
          <tns:sakWorkflow>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:WORKFLOWID"/>
          </tns:sakWorkflow>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:StatusSimpleType/ns5:STATUSID">
          <tns:sakStatus>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:StatusSimpleType/ns5:STATUSID"/>
          </tns:sakStatus>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:StatusSimpleType/ns5:STATUSNAME">
          <tns:namStatus>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:StatusSimpleType/ns5:STATUSNAME"/>
          </tns:namStatus>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:QueueSimpleType/ns5:QUEUEID">
          <tns:sakQueue>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:QueueSimpleType/ns5:QUEUEID"/>
          </tns:sakQueue>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:QueueSimpleType/ns5:QUEUENAME">
          <tns:namQueue>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:QueueSimpleType/ns5:QUEUENAME"/>
          </tns:namQueue>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Tracking Number']/ns5:PROPERTYVALUE">
          <tns:txtTrackingnumber>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Tracking Number']/ns5:PROPERTYVALUE"/>
          </tns:txtTrackingnumber>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PA Number']/ns5:PROPERTYVALUE">
          <tns:txtPanumber>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PA Number']/ns5:PROPERTYVALUE"/>
          </tns:txtPanumber>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Assignment']/ns5:PROPERTYVALUE">
          <tns:txtAssignment>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Assignment']/ns5:PROPERTYVALUE"/>
          </tns:txtAssignment>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Date Received']/ns5:PROPERTYVALUE !='-' ">
          <tns:dteDatereceived>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Date Received']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteDatereceived>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Cornelius Due Date']/ns5:PROPERTYVALUE !='-'">
          <tns:dteCorneliusduedate>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Cornelius Due Date']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteCorneliusduedate>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Member ID']/ns5:PROPERTYVALUE">
          <tns:txtMemberid>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Member ID']/ns5:PROPERTYVALUE"/>
          </tns:txtMemberid>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Attach Ind']/ns5:PROPERTYVALUE">
          <tns:txtAttachid>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Attach Ind']/ns5:PROPERTYVALUE"/>
          </tns:txtAttachid>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PAS Number']/ns5:PROPERTYVALUE">
          <tns:txtPasnumber>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PAS Number']/ns5:PROPERTYVALUE"/>
          </tns:txtPasnumber>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Admission Date']/ns5:PROPERTYVALUE !='-'">
          <tns:dteAdmissiondate>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Admission Date']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteAdmissiondate>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Member Name']/ns5:PROPERTYVALUE">
          <tns:txtMembername>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Member Name']/ns5:PROPERTYVALUE"/>
          </tns:txtMembername>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Facility Name']/ns5:PROPERTYVALUE">
          <tns:txtFacilityname>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Facility Name']/ns5:PROPERTYVALUE"/>
          </tns:txtFacilityname>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Assigned Date']/ns5:PROPERTYVALUE != '-' ">
          <tns:dteAssigneddate>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Assigned Date']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteAssigneddate>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='MH Review Type']/ns5:PROPERTYVALUE">
          <tns:txtMhreviewtype>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='MH Review Type']/ns5:PROPERTYVALUE"/>
          </tns:txtMhreviewtype>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Deferred Date']/ns5:PROPERTYVALUE !='-'">
          <tns:dteDeffereddate>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Deferred Date']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteDeffereddate>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PCC']/ns5:PROPERTYVALUE">
          <tns:txtPcc>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='PCC']/ns5:PROPERTYVALUE"/>
          </tns:txtPcc>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Submission Type']/ns5:PROPERTYVALUE">
          <tns:txtSubmissiontype>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Submission Type']/ns5:PROPERTYVALUE"/>
          </tns:txtSubmissiontype>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Status Date']/ns5:PROPERTYVALUE !='-'">
          <tns:dteStatusdate>
            <xsl:call-template name="formatDate">
              <xsl:with-param name="dateParam"
                              select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Status Date']/ns5:PROPERTYVALUE"/>
            </xsl:call-template>
          </tns:dteStatusdate>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='NPI']/ns5:PROPERTYVALUE">
          <tns:txtNpi>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='NPI']/ns5:PROPERTYVALUE"/>
          </tns:txtNpi>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Service Location']/ns5:PROPERTYVALUE">
          <tns:txtServicelocation>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Service Location']/ns5:PROPERTYVALUE"/>
          </tns:txtServicelocation>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Provider Type']/ns5:PROPERTYVALUE">
          <tns:txtProvidertype>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Provider Type']/ns5:PROPERTYVALUE"/>
          </tns:txtProvidertype>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='DBA Name']/ns5:PROPERTYVALUE">
          <tns:txtDbaname>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='DBA Name']/ns5:PROPERTYVALUE"/>
          </tns:txtDbaname>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='SSN/FEIN']/ns5:PROPERTYVALUE">
          <tns:txtSsnFein>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='SSN/FEIN']/ns5:PROPERTYVALUE"/>
          </tns:txtSsnFein>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Internal ATN']/ns5:PROPERTYVALUE">
          <tns:txtInternalatn>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Internal ATN']/ns5:PROPERTYVALUE"/>
          </tns:txtInternalatn>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='External ATN']/ns5:PROPERTYVALUE">
          <tns:txtExternalatn>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='External ATN']/ns5:PROPERTYVALUE"/>
          </tns:txtExternalatn>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Reason Code']/ns5:PROPERTYVALUE">
          <tns:txtReasoncode>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Reason Code']/ns5:PROPERTYVALUE"/>
          </tns:txtReasoncode>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Document Type']/ns5:PROPERTYVALUE">
          <tns:txtDocumenttype>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Document Type']/ns5:PROPERTYVALUE"/>
          </tns:txtDocumenttype>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Update Type']/ns5:PROPERTYVALUE">
          <tns:txtUpdatetype>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Update Type']/ns5:PROPERTYVALUE"/>
          </tns:txtUpdatetype>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Provider ID/Loc']/ns5:PROPERTYVALUE">
          <tns:txtProvideridLoc>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='Provider ID/Loc']/ns5:PROPERTYVALUE"/>
          </tns:txtProvideridLoc>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='View Image']/ns5:PROPERTYVALUE">
          <tns:txtViewimage>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='View Image']/ns5:PROPERTYVALUE"/>
          </tns:txtViewimage>
        </xsl:if>
        <xsl:if test="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='SAK_PROV_XML']/ns5:PROPERTYVALUE">
          <tns:txtSakProvXml>
            <xsl:value-of select="/ns0:updateWorkflowAuditRequest/ns5:WorkflowTaskUpdateXML/ns5:CustomPropertyType[ns5:PROPERTYNAME='SAK_PROV_XML']/ns5:PROPERTYVALUE"/>
          </tns:txtSakProvXml>
        </xsl:if>
      </tns:TWorkflowAuditdetail>
    </tns:TWorkflowAuditdetailCollection>
  </xsl:template>
  <xsl:template name="formatDate">
    <xsl:param name="dateParam"/>
    <xsl:value-of select="concat(concat(substring($dateParam,7,4),'-',substring($dateParam,1,2),'-',substring($dateParam,4,2)),'T00:00:00.000Z')"/>
  </xsl:template>
</xsl:stylesheet>
