<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns4="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmiscommon"
                xmlns:ns1="http://newmmis.eohhs.ma.gov/mmisWorkflowCustomAuditHandler/RecordBPMTaskCreation"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                xmlns:ns2="http://newmmis.eohhs.ma.gov/serviceobjects/versions/1.0/mmisWorkflowFault"
                xmlns:ns3="http://newmmis.eohhs.ma.gov/worklist/xml"
                xmlns:ns5="http://newmmis.eohhs.ma.gov/workflows/xml"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/UtilitiesApplication/WorkflowCustomAuditHandlerProject/Insert_WorkflowAuditDetail"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOABundles/WSDL/UtilityService/RecordBPMTaskCreation.wsdl"/>
        <oracle-xsl-mapper:rootElement name="recordBPMTaskCreationRequest"
                                       namespace="http://newmmis.eohhs.ma.gov/schema/mmisWorkflowUtilityServices"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/Insert_WorkflowAuditDetail.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TWorkflowAuditdetailCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_WorkflowAuditDetail"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.2(XSLT Build 150402.0900.0103) AT [THU JUL 09 12:31:58 CDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:TWorkflowAuditdetailCollection>
      <tns:TWorkflowAuditdetail>
        <xsl:if test="/ns0:recordBPMTaskCreationRequest/ns0:sak_workflowaudit">
          <tns:sakWorkflowaudit>
            <xsl:value-of select="/ns0:recordBPMTaskCreationRequest/ns0:sak_workflowaudit"/>
          </tns:sakWorkflowaudit>
        </xsl:if>
        <xsl:if test="/ns0:recordBPMTaskCreationRequest/ns0:GUID">
          <tns:idGuid>
            <xsl:value-of select="/ns0:recordBPMTaskCreationRequest/ns0:GUID"/>
          </tns:idGuid>
        </xsl:if>
        <xsl:if test="/ns0:recordBPMTaskCreationRequest/ns0:TaskId">
          <tns:idTask>
            <xsl:value-of select="/ns0:recordBPMTaskCreationRequest/ns0:TaskId"/>
          </tns:idTask>
        </xsl:if>
        <xsl:if test="/ns0:recordBPMTaskCreationRequest/ns0:ECID">
          <tns:idEcid>
            <xsl:value-of select="/ns0:recordBPMTaskCreationRequest/ns0:ECID"/>
          </tns:idEcid>
        </xsl:if>
        <tns:cdeWorkflowAction>B</tns:cdeWorkflowAction>
        <tns:dteActivitystart>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:dteActivitystart>
        <tns:dteActivitycompletion>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </tns:dteActivitycompletion>
        <tns:txtActivitypayload>NotApplicable</tns:txtActivitypayload>
        <tns:idClerk>ORABPM</tns:idClerk>
        <xsl:if test="/ns0:recordBPMTaskCreationRequest/ns0:Sak_Workflow">
          <tns:sakWorkflow>
            <xsl:value-of select="/ns0:recordBPMTaskCreationRequest/ns0:Sak_Workflow"/>
          </tns:sakWorkflow>
        </xsl:if>
      </tns:TWorkflowAuditdetail>
    </tns:TWorkflowAuditdetailCollection>
  </xsl:template>
</xsl:stylesheet>
